### ISSUE TITLE
How can I get the scrape document?

### ISSUE THREAD

**Issue by chickenCabbage** [gabceb/node-metainspector#42]
After I scrape a document with node-metainspector and analyze it, I'd like to access the received HTML. How can I do this?

**Comment by gabceb** [comment]
Code below should do it

```javascript
var Metainspector = require('node-metainspector');

var client = new Metainspector('https://www.google.com/');
client.on('fetch', function() {
  // Do whatever you need with the document here now that we have fetched it
  console.log(client.document);
});

client.fetch();
```

**Comment by chickenCabbage** [comment]
And is it plaintext or is it an object?
Can I do `client.document.getElementById()`? because that would make my life lovley.

**Comment by gabceb** [comment]
Its a string but you can use client.parsedDocument which is the body parsed by cheerio which allows you to find elements jquery style. To find a specific element with an id you would use client.parsedDocument("#element")

**Comment by chickenCabbage** [comment]
Alright thanks a lot!
